### ISSUE TITLE
Frozen Jet Game Crash

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#106]
Game crashes during the frozen jet animation

Caused by: java.lang.UnsupportedOperationException: There is no method at 10a3fc. The value is 27bdffb8.

java.lang.RuntimeException: Script subfunc 851 error
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3988)
	at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3594)
	at legend.game.Scus94491BpeSegment.executeScripts1(Scus94491BpeSegment.java:2984)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:1001)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:845)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:519)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: There is no method at 10a3fc. The value is 27bdffb8.
	at legend.core.memory.Segment.getFunction(Segment.java:81)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:414)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
Caused by: java.lang.UnsupportedOperationException: There is no method at 10a3fc. The value is 27bdffb8.

	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3986)
	... 15 more

**Comment by dragoonsouls** [comment]
With new changes i tried this spell and still game-crash
00:02:38.142 [GPU legend.core.gpu.Gpu:430] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: Script subfunc 851 error
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3596)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:426)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3190)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:2596)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:939)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:785)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:390)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:428)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: There is no method at 10a3fc. The value is 27bdffb8.
	at legend.core.memory.Segment.getFunction(Segment.java:81)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:415)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3594)
	... 15 more
