### ISSUE TITLE
Selecting Power Down crashes the game

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#107]
Selecting Power Down from the battle menu item inventory crashes the game, the target selection screen does not show up.
java.lang.IllegalArgumentException: Overflow: -50
	at legend.core.memory.types.UnsignedByteRef.set(UnsignedByteRef.java:35)
	at legend.game.combat.Bttl_800f.setTempWeaponStats(Bttl_800f.java:3486)
	at legend.game.combat.Bttl_800f.FUN_800f4b80(Bttl_800f.java:2150)
	at legend.game.combat.Bttl_800e.FUN_800ef9e4(Bttl_800e.java:6241)
	at legend.game.combat.Bttl_800c.FUN_800c7bb8(Bttl_800c.java:1079)
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.FUN_800186a0(Scus94491BpeSegment.java:4883)
	at legend.game.Scus94491BpeSegment.FUN_80018658(Scus94491BpeSegment.java:4876)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:999)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:845)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:519)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
This is no longer an issue as of bobjs being dememulated
