### ISSUE TITLE
Crashing in "in-Battle" Cutscene after defeating Mappi in Barrens

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#116]
Here i'll post the log of the error:
legend.core.memory.IllegalAddressException: There is no memory segment at 500000 (address: 80500000)
	at legend.core.memory.Memory.getSegment(Memory.java:119)
	at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:342)
	at legend.core.memory.Memory$MemoryValue.set(Memory.java:453)
	at legend.core.memory.Memory$MemoryValue.setu(Memory.java:467)
	at legend.game.combat.SEffe.FUN_80109358(SEffe.java:5204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.combat.Bttl_800e.FUN_800e8e9c(Bttl_800e.java:3847)
	at jdk.internal.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.Scus94491BpeSegment.executeScriptTickers(Scus94491BpeSegment.java:4406)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:2981)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:997)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:840)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:517)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:553)
	at java.base/java.lang.Thread.run(Thread.java:833)
01:15:36.645 [Code legend.core.kernel.Bios:484] INFO : Exiting

//// As side note, it's in the part in which the CTMD of the Red-Eyed Dragon Spirit is shown!...

**Comment by dragoonsouls** [comment]
As talk... seems to be a error in the reading of RAM... (read from 0 to the end in a single cycle [?])
