### ISSUE TITLE
Demon's Gate /0

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#120]
```
java.lang.ArithmeticException: / by zero
	at legend.core.memory.types.IntRef.div(IntRef.java:72)
	at legend.core.gte.VECTOR.div(VECTOR.java:207)
	at legend.game.combat.SEffe.FUN_80110aa8(SEffe.java:7392)
	at legend.game.combat.SEffe.FUN_801121fc(SEffe.java:7860)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3982)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3590)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:2980)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:997)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:840)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:517)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:553)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
Resolved in graphics rewrite
