### ISSUE TITLE
Pressing "up" in the armed menu with no free equipment in inventory crashes game

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#127]
![image](https://user-images.githubusercontent.com/114020799/194682626-adde8f05-0d23-452c-84db-beadc0b9fc72.png)
This is from early Hellena (visit 1). I got the leather jacket and tried to equip it to Dart (not realizing it was not his equipment). I opened the Armed menu and saw the blank list posted above. I accidentally hit the up key at this point and the game immediately crashed. All other keys seem to be safe. We're probably jumping to the end of the list when I do that, but items[length-1] is not valid on an empty list

Stack trace:

20:06:11.949 [GPU legend.game.SItem:906] INFO : Inventory menu state: _15
20:06:11.950 [GPU legend.core.gpu.Gpu:541] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index -1 is out of bounds (0 <= n < 256)
	at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
	at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
	at legend.game.SItem.FUN_80102660(SItem.java:3062)
	at legend.game.SItem.FUN_800fcad4(SItem.java:1386)
	at legend.game.Scus94491BpeSegment_8002.FUN_80022590(Scus94491BpeSegment_8002.java:1681)
	at legend.game.SMap.executeSmapLoadingStage_2(SMap.java:4987)
	at legend.game.SMap.executeSmapLoadingStage(SMap.java:4782)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:993)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:840)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:503)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:539)
	at java.base/java.lang.Thread.run(Thread.java:833)
20:06:11.957 [Code legend.core.kernel.Bios:484] INFO : Exiting

**Comment by LordMonoxide** [comment]
Fixed in bfb0a7a
