### ISSUE TITLE
Kongol's Meteor Strike spell crashes game ("No memory segment")

### ISSUE THREAD

**Issue by djcarvey** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#155]
Casting Kongol's second spell causes a crash when the animation starts to play
Note that due to https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/issues/109 you will need to use the Special command to transform Kongol

19:09:31.807 [GPU legend.core.gpu.Gpu:548] ERROR: Shutting down due to GPU exception:
legend.core.memory.IllegalAddressException: There is no memory segment at 7bac28 (address: 7bac28)
	at legend.core.memory.Memory.getSegment(Memory.java:119)
	at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:342)
	at legend.core.memory.Memory$MemoryValue.get(Memory.java:402)
	at legend.core.memory.types.UnsignedIntRef.get(UnsignedIntRef.java:27)
	at legend.core.memory.types.UnsignedIntRef.and(UnsignedIntRef.java:128)
	at legend.game.Scus94491BpeSegment_8003.SetDrawMode(Scus94491BpeSegment_8003.java:1788)
	at legend.game.combat.SEffe.FUN_800fddd8(SEffe.java:1526)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.Scus94491BpeSegment.executeScriptRenderers(Scus94491BpeSegment.java:4390)
	at legend.game.Scus94491BpeSegment.renderScriptObjects(Scus94491BpeSegment.java:2940)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:997)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:841)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:510)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:546)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
This was fixed at some point
