### ISSUE TITLE
Violet Dragon Magic - VRAM corruption

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#157]
Violet Dragon Magic (spell) raise a GPU exception almost at the end of animation

00:50:52.395 [GPU legend.core.gpu.Gpu:548] ERROR: Shutting down due to GPU exception:
java.lang.IllegalArgumentException: Overflow: -1282
	at legend.core.memory.types.UnsignedIntRef.set(UnsignedIntRef.java:35)
	at legend.game.combat.Bttl_800d.FUN_800d247c(Bttl_800d.java:870)
	at jdk.internal.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.Scus94491BpeSegment.executeScriptRenderers(Scus94491BpeSegment.java:4389)
	at legend.game.Scus94491BpeSegment.renderScriptObjects(Scus94491BpeSegment.java:2939)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:996)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:840)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:510)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:546)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by dragoonsouls** [comment]
Now the Crash is solved, but seems to change only one (1) CLUT from the Textures from Battle Stages, as seen in this Screenshot
![1111](https://user-images.githubusercontent.com/17453375/205340329-0b832b83-5940-4ccb-a78b-e1f0b30996c2.png)
so i we update this simply as a visual bug...
