### ISSUE TITLE
Leaving Furni (to Evergreen Forest) ERROR

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#158]
An overflow error occurred when leaving Furni to Evergreen Forest... here is the log:

06:49:14.526 [GPU legend.core.gpu.Gpu:548] ERROR: Shutting down due to GPU exception:
java.lang.IllegalArgumentException: Overflow: -1
	at legend.core.memory.types.UnsignedByteRef.set(UnsignedByteRef.java:35)
	at legend.game.WMap.FUN_800eca3c(WMap.java:8572)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.WMap.FUN_800ed95c(WMap.java:8774)
	at legend.game.WMap.FUN_800cd030(WMap.java:1008)
	at legend.game.WMap.FUN_800cccbc(WMap.java:813)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.WMap.FUN_800ccb98(WMap.java:771)
	at legend.game.WMap.FUN_800cc738(WMap.java:650)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:993)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:840)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:510)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:546)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
Fixed in d490b14
