### ISSUE TITLE
When first time in Mille Sesesau World Map, Crash

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#159]
When leaving Furni for fist time, right after the loading the World Map, almost when the camera reach the ground level

23:55:17.815 [GPU legend.core.gpu.Gpu:548] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index 51097880 is out of bounds (0 <= n < 2)
	at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
	at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
	at legend.game.Scus94491BpeSegment.swapDisplayBuffer_24bpp(Scus94491BpeSegment.java:1929)
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.endFrame(Scus94491BpeSegment.java:1835)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:854)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:510)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:546)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
Fixed in graphics rewrite
