### ISSUE TITLE
Shiranda dragoon attack retail bug

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#168]
```
21:38:42.232 [GPU legend.core.gpu.Gpu:430] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index 128 is out of bounds (0 <= n < 128)
	at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
	at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
	at legend.game.combat.Bttl_800f.setTempSpellStats(Bttl_800f.java:3284)
	at legend.game.combat.Bttl_800f.FUN_800f96a8(Bttl_800f.java:3832)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:426)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3594)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:426)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3190)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:2596)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:939)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:785)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:390)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:428)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
This is difficult to fix as the root bug is in a script, so I'm adding a check to the method that's failing to skip the code if it has an invalid spell ID
