### ISSUE TITLE
Enter into Law Factory in Zenebatos Crash

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#172]
After few seconds of enter in the Law Factory raise an error that crash the game

17:36:49.026 [GPU legend.core.gpu.Gpu:439] ERROR: Shutting down due to GPU exception:
java.lang.AssertionError
	at legend.game.SMap.FUN_800f0644(SMap.java:8001)
	at legend.game.SMap.FUN_800ef0f8(SMap.java:7583)
	at legend.game.SMap.submapObjectRenderer(SMap.java:2704)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:442)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.Scus94491BpeSegment.executeScriptRenderers(Scus94491BpeSegment.java:3745)
	at legend.game.Scus94491BpeSegment.renderScriptObjects(Scus94491BpeSegment.java:2299)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:942)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:787)
	at legend.core.gpu.Gpu.lambda$run$5(Gpu.java:391)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:400)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:394)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:437)
	at java.base/java.lang.Thread.run(Thread.java:833)
17:36:49.037 [Code legend.core.kernel.Bios:459] INFO : Exiting
17:36:49.038 [Thread-3 legend.core.opengl.Window:85] INFO : Shutting down...

**Comment by LordMonoxide** [comment]
Resolved in last few commits
