### ISSUE TITLE
Three Executioners Crash - Selebus Special Attack Crash

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#174]
at.SEffe.FUN_80111ae4(SEffe.java:7577)
	at jdk.internal.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:442)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3286)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:442)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2882)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:2292)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:941)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:787)
	at legend.core.gpu.Gpu.lambda$run$5(Gpu.java:391)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:400)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:394)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:437)
	at java.base/java.lang.Thread.run(Thread.java:833)
19:25:33.291 [Code legend.core.kernel.Bios:459] INFO : Exiting
19:25:33.305 [Thread-3 legend.core.opengl.Window:85] INFO : Shutting down...

the crash occurs when Selebus do the Grab with zombie hands attack

**Comment by dragoonsouls** [comment]
[Whole_Crash_Selebus.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10099360/Whole_Crash_Selebus.txt)
This is the whole crash log

**Comment by dragoonsouls** [comment]
[state_Selebus_Crash.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10099408/state_Selebus_Crash.zip)

**Comment by dragoonsouls** [comment]
also Kubila is add to this problem... when using the Demonic "Frog" attack
this is the save file to play it as "in story mode"
[323.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10840972/323.zip)
