### ISSUE TITLE
NoDart transformation crash

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#177]
When replacing Dart with Albert, the game crashed at the end of Albert's Dragoon transformation. It was another variant of the script tick error:

```
Caused by: java.lang.IndexOutOfBoundsException: Index 3 is out of bounds (0 <= n < 3)
    at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
    at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
    at legend.game.Scus94491BpeSegment.FUN_8001cce8(Scus94491BpeSegment.java:5800)
    at legend.game.Scus94491BpeSegment.FUN_8001e920(Scus94491BpeSegment.java:6472)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at legend.core.memory.Memory$MemoryValue.call(Memory.java:462)
    at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
    at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3341)
    at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at legend.core.memory.Memory$MemoryValue.call(Memory.java:462)
    at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
    at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2934)
    ... 10 more
```

**Comment by DrewUniverse** [comment]
I encountered this error as well. Rose/Albert/Haschel, Albert Special, crash at end of transformation. 
`Caused by: java.lang.IndexOutOfBoundsException: Index 3 is out of bounds (0 <= n < 3)
        at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
        at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
        at legend.game.Scus94491BpeSegment.FUN_8001cce8(Scus94491BpeSegment.java:5223)
        at legend.game.Scus94491BpeSegment.FUN_8001e920(Scus94491BpeSegment.java:5900)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
        at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
        at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:2852)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
        at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
        at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2445)
        ... 10 more`

**Comment by LordMonoxide** [comment]
No longer an issue as of full file unpacking
