### ISSUE TITLE
32/64 Items Config bug (Crash)

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#187]
If you have 33 Items or more at the moment of change from 64 to 32, a crash will happens.
[33_Item_Bug.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10277877/33_Item_Bug.txt)

**Comment by Zychronix** [comment]
I have a similar crash but different error. This is crash is from the item replace screen.

21:03:15.243 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.NullPointerException: Pointer 800c43e0 is null
	at legend.core.memory.types.Pointer.deref(Pointer.java:73)
	at legend.game.Scus94491BpeSegment_8004.FUN_80048c38(Scus94491BpeSegment_8004.java:2429)
	at legend.game.Scus94491BpeSegment_8004.FUN_80048d44(Scus94491BpeSegment_8004.java:2470)
	at legend.game.Scus94491BpeSegment_8004.FUN_8004d648(Scus94491BpeSegment_8004.java:4348)
	at legend.game.Scus94491BpeSegment.FUN_8001a5fc(Scus94491BpeSegment.java:4373)
	at legend.game.Scus94491BpeSegment.FUN_8001a4e8(Scus94491BpeSegment.java:4353)
	at legend.game.Scus94491BpeSegment.FUN_8001aa24(Scus94491BpeSegment.java:4452)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:738)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:510)
	at legend.core.opengl.Window.run(Window.java:250)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
