### ISSUE TITLE
Gpu Exception during "cutscene"

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#188]
During the cutscene in Hellena when the Hellena guards are guiding the Basil guards, right before Lavits shows up, I got a GPU exception for an our of bounds error

```java
14:41:34.916 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index -1899478324 out of bounds for length 524288
	at legend.core.gpu.Gpu.getPixel15(Gpu.java:848)
	at legend.core.gpu.Gpu.get4bppTexel(Gpu.java:894)
	at legend.core.gpu.Gpu.getTexel(Gpu.java:883)
	at legend.core.gpu.GpuCommandQuad.render(GpuCommandQuad.java:110)
	at legend.core.gpu.Gpu.tick(Gpu.java:597)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:474)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:510)
	at legend.core.opengl.Window.run(Window.java:250)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by majorjae** [comment]
Same error occurs on Steam Deck which uses Arch Linux. However, I don't see any error logs.
