### ISSUE TITLE
Error while fighting Kongol in Hoax

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#191]
While fighting Kongol for the first time, immediately after his first attack, I received this error that crashed the game

```java
13:58:38.202 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 12
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2484)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:1891)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:808)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:733)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:510)
	at legend.core.opengl.Window.run(Window.java:250)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArithmeticException: / by zero
	at legend.game.Scus94491BpeSegment.FUN_80013404(Scus94491BpeSegment.java:1481)
	at legend.game.combat.Bttl_800c.FUN_800cdc1c(Bttl_800c.java:3766)
	at legend.game.combat.Bttl_800c.FUN_800cbb00(Bttl_800c.java:2962)
	at jdk.internal.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:2889)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2482)
	... 10 more
```

It's happened to me at least twice under conditions specified above

**Comment by zack37** [comment]
Certainly not the "correct" thing to do, but I was able to add
```java
    if(a2 == 0) {
      return 0;
    }
```
to `FUN_80013404` and I was able to move beyond this crash
