### ISSUE TITLE
GPU exception during intro cutscene directly after chapter 1 text leaves screen

### ISSUE THREAD

**Issue by Chro11oLuci** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#192]
21:41:41.334 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index 117 out of bounds for length 117
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at legend.game.SMap.executeSceneGraphicsLoadingStage(SMap.java:2723)
        at legend.game.SMap.executeSmapLoadingStage_2(SMap.java:4393)
        at legend.game.SMap.executeSmapLoadingStage(SMap.java:4242)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:806)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:733)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:510)
        at legend.core.opengl.Window.run(Window.java:250)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Chro11oLuci** [comment]
excuse terrible layout probably, don't use github to often
