### ISSUE TITLE
`AssertionError` during first Virage fight

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#193]
While fighting the first Virage in Volcano Villude, when Dart goes to deal the final blow, the game crashes with:

```java
14:15:18.882 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 20
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2488)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:1895)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:808)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:733)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:510)
	at legend.core.opengl.Window.run(Window.java:250)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError
	at legend.game.Scus94491BpeSegment_8004.FUN_8004cb0c(Scus94491BpeSegment_8004.java:3984)
	at legend.game.Scus94491BpeSegment.FUN_8001b208(Scus94491BpeSegment.java:4647)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:2893)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2486)
   ... 10 more
```

Can be reproduced (has happened twice in a row to me)

**Comment by zack37** [comment]
Potentially related:
When running into this bug originally, I had set the volume of the LoD app to 0. Settings it to 1, and doing nothing else, seems to have allowed me to move past the end of the fight

**Comment by LordMonoxide** [comment]
I haven't fully fixed this but temporarily patched it so it doesn't crash

**Comment by dragoonsouls** [comment]
atm in main.tmd we don't register any crash on it...
