### ISSUE TITLE
Using scrollwheel in equipment shop causes crash

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#201]
Went to buy gear in Lohan. After buying a few things, game crashed. Trace:

```
11:09:51.332 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.NullPointerException: Cannot assign field "x_40" because "this.charHighlight" is null
        at legend.game.inventory.screens.ShopScreen.scroll(ShopScreen.java:296)
        at legend.game.inventory.screens.ShopScreen.render(ShopScreen.java:203)
        at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:71)
        at legend.game.inventory.screens.MenuStack.render(MenuStack.java:46)
        at legend.game.Scus94491BpeSegment_8002.loadAndRenderMenus(Scus94491BpeSegment_8002.java:1432)
        at legend.game.SMap.executeSmapLoadingStage_2(SMap.java:4446)
        at legend.game.SMap.executeSmapLoadingStage(SMap.java:4242)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:449)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:803)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:730)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by DrewUniverse** [comment]
I think it happens whenever I scroll the mouse wheel, while viewing the equipment list.
