### ISSUE TITLE
Crash when re-entering the `Nest of Dragon` after leaving `Shrine of Shirley`

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#206]
As title states, I leave Shrine of Shirley after getting the White Dragoon Spirit, and then from the world map as I click enter on Nest of Dragon, the screen goes black and then the game crashes with:

```java
20:14:57.285 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.IllegalArgumentException: Overflow: 281474976677966
	at legend.core.memory.types.UnsignedIntRef.set(UnsignedIntRef.java:35)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:2224)
	at legend.game.Scus94491BpeSegment.tickScripts(Scus94491BpeSegment.java:1871)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:805)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:730)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
Many hours of research into the script engine lead me to believe this is a retail bug. It looks like the third submap object on the Nest of Dragon map has a bug that makes the execution pointer jump out of bounds into the next script in the MRG. This is causing a crash in SC since with full file unpacking we no longer use MRG files, and the script engine is just trying to execute whatever happens to be in RAM at that location.

It doesn't crash in retail because the offset it jumps to in the next script (which is in the middle of a command) just happens to cause the script engine to pause the current script's execution.
