### ISSUE TITLE
Main menu lock-up

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#22]
1. Entered first save point.
2. Opened main menu
3. Navigated to Save
4. Opened save menu
5. Exited save menu without doing anything
6. Controls stopped working

**Comment by LordMonoxide** [comment]
I just tested and got an exception:
` java.lang.NullPointerException: Pointer 8011dc98 is null
        at legend.core.memory.types.Pointer.deref(Pointer.java:71)
        at legend.game.SItem.messageBox(SItem.java:8734)
        at legend.game.SItem.FUN_800fcad4(SItem.java:1050)
        at legend.game.Scus94491BpeSegment_8002.FUN_80022590(Scus94491BpeSegment_8002.java:1691)
        at legend.game.SMap.executeSmapLoadingStage_2(SMap.java:6869)
        at legend.game.SMap.executeSmapLoadingStage(SMap.java:6650)
        at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:402)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:17)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:571)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$2(Scus94491BpeSegment.java:438)
        at legend.core.gpu.Gpu.lambda$run$11(Gpu.java:468)
        at legend.core.opengl.Context.draw(Context.java:96)
        at legend.core.opengl.Window$Events.onDraw(Window.java:336)
        at legend.core.opengl.Window.run(Window.java:217)
        at legend.core.gpu.Gpu.run(Gpu.java:475)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by LordMonoxide** [comment]
Resolved
