### ISSUE TITLE
Crash just before post-battle report (Fruegel II)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#229]
This occurred after the cutscene, but before the post-battle report could display. In case this caused it, Lavitz was the only party member alive. In retail, when Lavitz is the only survivor, no one gets EXP including the bench, so maybe SC didn't know what to do with that?

```21:22:10.288 [GPU legend.game.Scus94491BpeSegment:1715] INFO : Loading SECT/DRGN0.BIN/6666 from legend.game.SItem.renderPostCombatReport(SItem.java:2238)
21:22:10.288 [GPU legend.game.unpacker.Unpacker:64] INFO : Loading file SECT/DRGN0.BIN/6666
21:22:10.289 [GPU legend.game.Scus94491BpeSegment:1732] INFO : Executing file callback (param 00000001)
21:22:10.736 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.ArithmeticException: / by zero
        at legend.game.SItem.renderPostCombatReport(SItem.java:2311)
        at legend.game.Scus94491BpeSegment_8002.loadAndRenderMenus(Scus94491BpeSegment_8002.java:1436)
        at legend.game.Scus94491BpeSegment.FUN_80018508(Scus94491BpeSegment.java:2023)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
        at legend.game.Scus94491BpeSegment.FUN_800186a0(Scus94491BpeSegment.java:2080)
        at legend.game.Scus94491BpeSegment.FUN_80018658(Scus94491BpeSegment.java:2066)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:780)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
This is caused by retail silently ignoring the /0 bug, which would result in -1 XP for the result. But, because XP for secondary party members is halved, it ends up as 0.

We may want to rework how XP is granted, because in retail, technically the most efficient way to level your whole party is to play solo.
