### ISSUE TITLE
After killing Windigo, Haschel did not unload after the submap cutscene and animated with garbage data

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#233]
```
19:38:38.244 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804dff68 (animation 804df13c)
19:38:38.245 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 15 (SubmapObject210)
19:38:38.245 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 5 into index 15 (entry point 0x0)
19:38:38.245 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804dbb5c (animation 804dae98)
19:38:38.245 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 16 (SubmapObject210)
19:38:38.245 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 6 into index 16 (entry point 0x0)
19:38:38.245 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804d67c8 (animation 804d5c84)
19:38:38.245 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 17 (SubmapObject210)
19:38:38.245 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 7 into index 17 (entry point 0x0)
19:38:38.246 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804d4850 (animation 804d4804)
19:38:38.246 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 18 (SubmapObject210)
19:38:38.246 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 8 into index 18 (entry point 0x0)
19:38:38.246 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804d4338 (animation 804d42ec)
19:38:38.308 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804d20a8 (animation 804d205c)
Feb 03, 2023 7:39:31 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @768debd'
19:39:51.875 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
legend.core.memory.IllegalAddressException: There is no memory segment at 500006 (address: 80500006)
        at legend.core.memory.Memory.getSegment(Memory.java:118)
        at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:362)
        at legend.core.memory.Memory$MemoryValue.get(Memory.java:419)
        at legend.core.memory.types.ShortRef.get(ShortRef.java:27)
        at legend.core.gte.SVECTOR.getX(SVECTOR.java:71)
        at legend.game.SMap.FUN_800da920(SMap.java:999)
        at legend.game.SMap.FUN_800da114(SMap.java:852)
        at legend.game.Scus94491BpeSegment_8002.animateModel(Scus94491BpeSegment_8002.java:494)
        at legend.game.SMap.submapObjectTicker(SMap.java:2439)
        at legend.game.scripting.ScriptState.tick(ScriptState.java:170)
        at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:171)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:24)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by theflyingzamboni** [comment]
Possibly related; occurred after Lavitz explosively breakdancing for a minute or two outside the arena while talking to Dart about how much of a putz he is:

```
23:56:20.232 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
legend.core.memory.IllegalAddressException: There is no memory segment at 500006 (address: 80500006)
    at legend.core.memory.Memory.getSegment(Memory.java:118)
    at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:362)
    at legend.core.memory.Memory$MemoryValue.get(Memory.java:419)
    at legend.core.memory.types.ShortRef.get(ShortRef.java:27)
    at legend.core.gte.SVECTOR.getX(SVECTOR.java:71)
    at legend.game.SMap.FUN_800da920(SMap.java:999)
    at legend.game.SMap.FUN_800da114(SMap.java:852)
    at legend.game.Scus94491BpeSegment_8002.animateModel(Scus94491BpeSegment_8002.java:494)
    at legend.game.SMap.submapObjectTicker(SMap.java:2439)
    at legend.game.scripting.ScriptState.tick(ScriptState.java:170)
    at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:171)
    at legend.game.scripting.ScriptManager.tick(ScriptManager.java:24)
    at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
    at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
    at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
    at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
    at legend.core.opengl.Context.draw(Context.java:91)
    at legend.core.opengl.Window$Events.onDraw(Window.java:518)
    at legend.core.opengl.Window.run(Window.java:258)
    at legend.core.gpu.Gpu.run(Gpu.java:424)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
Resolved
