### ISSUE TITLE
Crash during cutscene after fight with Mappi and Gerich

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#235]
During the cut scene after fighting Mappi and Gerich when Kongol comes to save the day, I receive a crash:
```java
14:37:34.842 [GPU legend.game.Scus94491BpeSegment:1715] INFO : Loading SECT/DRGN0.BIN/618 from legend.game.combat.Bttl_800c.FUN_800cac38(Bttl_800c.java:2371)
14:37:34.842 [GPU legend.game.unpacker.Unpacker:64] INFO : Loading file SECT/DRGN0.BIN/618
14:37:34.845 [GPU legend.game.Scus94491BpeSegment:1732] INFO : Executing file callback (param 00000058)
14:37:34.892 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 28 (BattleObject27c)
14:37:34.892 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 5550/1 into index 28 (entry point 0x1)
14:37:34.892 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 8048a030 (animation 804d133c)
14:37:34.942 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
	at legend.game.combat.Bttl_800c.FUN_800c7304(Bttl_800c.java:827)
	at legend.game.Scus94491BpeSegment.FUN_80018744(Scus94491BpeSegment.java:2100)
	at legend.game.Scus94491BpeSegment.FUN_800186a0(Scus94491BpeSegment.java:2072)
	at legend.game.Scus94491BpeSegment.FUN_80018658(Scus94491BpeSegment.java:2066)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:780)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Worth noting that if I add some safety checks to the loop referenced above
(ex. )
```java
      if((bobjState.storage_44[7] & 0x40) == 0 && a1 < _8006e398.bobjIndices_e78.length) {
        _8006e398.bobjIndices_e78[a1] = bobjState;
        a1++;
      }
```

then the code below on line 1280 in the same file crashes because `combatant` is null
```java
        //LAB_800c8418
        //LAB_800c8434
        if(combatant.mrg_00 != null) {
          free(combatant.mrg_00.getAddress());
          combatant.mrg_00 = null;
        }
```

**Comment by LordMonoxide** [comment]
Crash point reference: https://www.youtube.com/watch?v=_wtLH3UoMoc&t=437s
