### ISSUE TITLE
Snowfield Crash: Cutscene of Dart/Lloyd entering shelter

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#236]
```18:06:09.694 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804cb21c (animation 804ca3f0)
18:06:09.694 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 16 (SubmapObject210)
18:06:09.694 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 6 into index 16 (entry point 0x0)
18:06:09.696 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804c5630 (animation 804c4aec)
18:06:09.697 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 17 (SubmapObject210)
18:06:09.697 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 7 into index 17 (entry point 0x0)
18:06:09.697 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804bd374 (animation 804bc440)
18:06:09.698 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 18 (SubmapObject210)
18:06:09.698 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Submap object 8 into index 18 (entry point 0x0)
18:06:09.698 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804b7ed0 (animation 804b7e84)
18:06:29.956 [GPU legend.game.scripting.ScriptManager:130] ERROR: Script 17 crashed!
18:06:29.956 [GPU legend.game.scripting.ScriptManager:131] ERROR: File Submap object 7[51]
18:06:29.958 [GPU legend.game.scripting.ScriptManager:132] ERROR: Parameters:
18:06:29.958 [GPU legend.game.scripting.ScriptManager:133] ERROR:   Op param: 0x0
18:06:29.959 [GPU legend.game.scripting.ScriptManager:135] ERROR:   1: script[0x2f6] 0x3
18:06:29.959 [GPU legend.game.scripting.ScriptManager:135] ERROR:   2: script[0x36d] 0xffffffff
18:06:29.959 [GPU legend.game.scripting.ScriptManager:135] ERROR:   3: script[17].storage[8] -1
18:06:29.959 [GPU legend.game.scripting.ScriptManager:138] ERROR: Storage:
18:06:29.959 [GPU legend.game.scripting.ScriptManager:140] ERROR:   1: 0x11
18:06:29.961 [GPU legend.game.scripting.ScriptManager:140] ERROR:   2: 0xffffffff
18:06:29.962 [GPU legend.game.scripting.ScriptManager:140] ERROR:   3: 0xffffffff
18:06:29.962 [GPU legend.game.scripting.ScriptManager:140] ERROR:   4: 0xffffffff
18:06:29.962 [GPU legend.game.scripting.ScriptManager:140] ERROR:   5: 0xffffffff
18:06:29.962 [GPU legend.game.scripting.ScriptManager:140] ERROR:   6: 0xffffffff
18:06:29.963 [GPU legend.game.scripting.ScriptManager:140] ERROR:   7: 0xffffffff
18:06:29.963 [GPU legend.game.scripting.ScriptManager:140] ERROR:   8: 0x10000
18:06:29.963 [GPU legend.game.scripting.ScriptManager:140] ERROR:   9: 0xffffffff
18:06:29.963 [GPU legend.game.scripting.ScriptManager:140] ERROR:   10: 0xfffffd11
18:06:29.963 [GPU legend.game.scripting.ScriptManager:140] ERROR:   11: 0x19c
18:06:29.964 [GPU legend.game.scripting.ScriptManager:140] ERROR:   12: 0xffffffff
18:06:29.964 [GPU legend.game.scripting.ScriptManager:140] ERROR:   13: 0xffffffff
18:06:29.964 [GPU legend.game.scripting.ScriptManager:140] ERROR:   14: 0xffffffff
18:06:29.964 [GPU legend.game.scripting.ScriptManager:140] ERROR:   15: 0xffffffff
18:06:29.964 [GPU legend.game.scripting.ScriptManager:140] ERROR:   16: 0xffffffff
18:06:29.965 [GPU legend.game.scripting.ScriptManager:140] ERROR:   17: 0xffffffff
18:06:29.965 [GPU legend.game.scripting.ScriptManager:140] ERROR:   18: 0xffffffff
18:06:29.965 [GPU legend.game.scripting.ScriptManager:140] ERROR:   19: 0xffffffff
18:06:29.965 [GPU legend.game.scripting.ScriptManager:140] ERROR:   20: 0xffffffff
18:06:29.965 [GPU legend.game.scripting.ScriptManager:140] ERROR:   21: 0x0
18:06:29.966 [GPU legend.game.scripting.ScriptManager:140] ERROR:   22: 0x6
18:06:29.966 [GPU legend.game.scripting.ScriptManager:140] ERROR:   23: 0xc
18:06:29.966 [GPU legend.game.scripting.ScriptManager:140] ERROR:   24: 0x0
18:06:29.966 [GPU legend.game.scripting.ScriptManager:140] ERROR:   25: 0x11
18:06:29.966 [GPU legend.game.scripting.ScriptManager:140] ERROR:   26: 0x0
18:06:29.967 [GPU legend.game.scripting.ScriptManager:140] ERROR:   27: 0x165
18:06:29.967 [GPU legend.game.scripting.ScriptManager:140] ERROR:   28: 0x3000
18:06:29.967 [GPU legend.game.scripting.ScriptManager:140] ERROR:   29: 0x9b3
18:06:29.967 [GPU legend.game.scripting.ScriptManager:140] ERROR:   30: 0x84e
18:06:29.967 [GPU legend.game.scripting.ScriptManager:140] ERROR:   31: 0x0
18:06:29.968 [GPU legend.game.scripting.ScriptManager:140] ERROR:   32: 0x0
18:06:29.968 [GPU legend.game.scripting.ScriptManager:140] ERROR:   33: 0x0
18:06:29.968 [GPU legend.game.scripting.ScriptManager:143] ERROR: Call stack:
18:06:29.968 [GPU legend.game.scripting.ScriptManager:149] ERROR:   1: 854
18:06:29.968 [GPU legend.game.scripting.ScriptManager:149] ERROR:   2: 0
18:06:29.969 [GPU legend.game.scripting.ScriptManager:149] ERROR:   3: 0
18:06:29.969 [GPU legend.game.scripting.ScriptManager:149] ERROR:   4: 0
18:06:29.969 [GPU legend.game.scripting.ScriptManager:149] ERROR:   5: 0
18:06:29.969 [GPU legend.game.scripting.ScriptManager:149] ERROR:   6: 0
18:06:29.970 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 17
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:152)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 878 out of bounds for length 878
        at legend.game.scripting.ScriptFile.getOp(ScriptFile.java:25)
        at legend.game.scripting.ScriptInlineParam.get(ScriptInlineParam.java:26)
        at legend.game.scripting.ScriptState.scriptMemCopy(ScriptState.java:662)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:498)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:462)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:126)
        ... 10 more```

**Comment by LordMonoxide** [comment]
This seems to be the exact same as the crash @zack37 got in the Kazas trash compactor:

```
15:03:22.169 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804d31e4 (animation 804d31a4)
15:03:22.235 [GPU legend.game.Scus94491BpeSegment_8002:384] INFO : Loading scripted TMD 804cf37c (animation 804cf330)
15:03:35.334 [GPU legend.game.scripting.ScriptManager:130] ERROR: Script 12 crashed!
15:03:35.334 [GPU legend.game.scripting.ScriptManager:131] ERROR: File Submap object 2[51]
15:03:35.334 [GPU legend.game.scripting.ScriptManager:132] ERROR: Parameters:
15:03:35.334 [GPU legend.game.scripting.ScriptManager:133] ERROR:   Op param: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:135] ERROR:   1: script[0x2f6] 0x3
15:03:35.334 [GPU legend.game.scripting.ScriptManager:135] ERROR:   2: script[0x36d] 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:135] ERROR:   3: script[12].storage[8] -1
15:03:35.334 [GPU legend.game.scripting.ScriptManager:138] ERROR: Storage:
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   1: 0xc
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   2: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   3: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   4: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   5: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   6: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   7: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   8: 0x10000
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   9: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   10: 0x2c
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   11: 0x1a2
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   12: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   13: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   14: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   15: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   16: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   17: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   18: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   19: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   20: 0xffffffff
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   21: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   22: 0x6
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   23: 0xc
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   24: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   25: 0xc
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   26: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   27: 0xa3
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   28: 0x3000
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   29: 0x66d
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   30: 0x5ca
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   31: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   32: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:140] ERROR:   33: 0x0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:143] ERROR: Call stack:
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   1: 854
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   2: 0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   3: 0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   4: 0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   5: 0
15:03:35.334 [GPU legend.game.scripting.ScriptManager:149] ERROR:   6: 0
15:03:35.335 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 12
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:152)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 878 out of bounds for length 878
	at legend.game.scripting.ScriptFile.getOp(ScriptFile.java:25)
	at legend.game.scripting.ScriptInlineParam.get(ScriptInlineParam.java:26)
	at legend.game.scripting.ScriptState.scriptMemCopy(ScriptState.java:662)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:498)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:462)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:126)
	... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 878 out of bounds for length 878
```
