### ISSUE TITLE
Crash in Jiango Battle - Ceiling Attack

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#242]
During Jiango Ceiling Attack, game crash.
I will post the entire run log
[Jiango_Crash_Ceiling_Attack.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10669935/Jiango_Crash_Ceiling_Attack.txt)

**Comment by LordMonoxide** [comment]
This also appears to be an animation failing to stop.

Trace:
```
legend.core.memory.IllegalAddressException: There is no memory segment at 500084 (address: 80500084)
	at legend.core.memory.Memory.getSegment(Memory.java:118)
	at legend.core.memory.Memory$MemoryValue.getSegment(Memory.java:362)
	at legend.core.memory.Memory$MemoryValue.get(Memory.java:419)
	at legend.core.memory.types.ShortRef.get(ShortRef.java:27)
	at legend.core.gte.SVECTOR.getX(SVECTOR.java:71)
	at legend.core.gte.SVECTOR.set(SVECTOR.java:35)
	at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:789)
	at legend.game.combat.Bttl_800d.applyStandardAnimation(Bttl_800d.java:4458)
	at legend.game.combat.Bttl_800d.applyAnimation(Bttl_800d.java:4860)
	at legend.game.combat.Bttl_800e.FUN_800ea3f8(Bttl_800e.java:4179)
	at legend.game.combat.Bttl_800e.effectManagerTicker(Bttl_800e.java:3672)
	at legend.game.scripting.ScriptState.tick(ScriptState.java:170)
	at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:171)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:24)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
No longer happening
