### ISSUE TITLE
Crash at first encounter following psychedelic bomb test in Aglis

### ISSUE THREAD

**Issue by keinengott** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#250]
18:53:39.746 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Combatant 0 into index 12 (entry point 0x0)
18:53:39.793 [GPU legend.game.Scus94491BpeSegment:1682] INFO : Loading DRGN0 dir 4113 from legend.game.combat.Bttl_800f.loadBattleHudTextures(Bttl_800f.java:3418)
18:53:39.794 [GPU legend.game.unpacker.Unpacker:82] INFO : Loading directory SECT/DRGN0.BIN/4113
18:53:39.809 [GPU legend.game.Scus94491BpeSegment:1693] INFO : Loading DRGN0 dir 4114/2 from legend.game.combat.Bttl_800e.loadBattleHudDeff(Bttl_800e.java:2661)
18:53:39.809 [GPU legend.game.unpacker.Unpacker:82] INFO : Loading directory SECT/DRGN0.BIN/4114/2
18:53:39.908 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: Found CTMD!
	at legend.game.Scus94491BpeSegment_8003.adjustTmdPointers(Scus94491BpeSegment_8003.java:970)
	at legend.game.combat.Bttl_800e.FUN_800ea620(Bttl_800e.java:2497)
	at legend.game.combat.Bttl_800e.hudDeffLoaded(Bttl_800e.java:2525)
	at legend.game.Scus94491BpeSegment.loadDrgnDir(Scus94491BpeSegment.java:1695)
	at legend.game.combat.Bttl_800e.loadBattleHudDeff(Bttl_800e.java:2661)
	at legend.game.combat.Bttl_800e.loadBattleHudDeff_(Bttl_800e.java:1947)
	at legend.game.combat.Bttl_800c.FUN_800c7964(Bttl_800c.java:931)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.FUN_800186a0(Scus94491BpeSegment.java:2073)
	at legend.game.Scus94491BpeSegment.FUN_80018658(Scus94491BpeSegment.java:2066)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:780)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
	at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:424)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by keinengott** [comment]
Repeatable: Go out left exit and initiate an encounter. Save file attached with extension changed to txt due to github upload requirements.
[67.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10738147/67.txt)

**Comment by keinengott** [comment]
Resolved by deleting files directory
