### ISSUE TITLE
Crash: D-Magic (Grand Stream)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#251]
Crashes near the end of the spell, as the rolling wave is about to hit the target.

```16:11:31.802 [GPU legend.game.combat.Bttl_800e:1678] INFO : Allocating memulated effect manager 12 for GuardHealEffect14 (parent: 13) @ 804f73ec from legend.game.combat.SEffe.allocateGuardHealEffect(SEffe.java:9825)
16:11:31.803 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4198/1 into index 12 (entry point 0x15)
16:11:31.803 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 14 (EffectManagerData6c)
16:11:31.803 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 14 (entry point 0x0)
16:11:31.803 [GPU legend.game.combat.Bttl_800e:1678] INFO : Allocating memulated effect manager 14 for GuardHealEffect14 (parent: 13) @ 804f732c from legend.game.combat.SEffe.allocateGuardHealEffect(SEffe.java:9825)
16:11:31.804 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4198/1 into index 14 (entry point 0x16)
16:11:31.804 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 17 (EffectManagerData6c)
16:11:31.804 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 17 (entry point 0x0)
16:11:31.804 [GPU legend.game.combat.Bttl_800e:1678] INFO : Allocating memulated effect manager 17 for GuardHealEffect14 (parent: 13) @ 804f730c from legend.game.combat.SEffe.allocateGuardHealEffect(SEffe.java:9825)
16:11:31.866 [GPU legend.game.scripting.ScriptManager:130] ERROR: Script 12 crashed!
16:11:31.866 [GPU legend.game.scripting.ScriptManager:131] ERROR: File 4198/1[5488]
16:11:31.867 [GPU legend.game.scripting.ScriptManager:132] ERROR: Parameters:
16:11:31.867 [GPU legend.game.scripting.ScriptManager:133] ERROR:   Op param: 0x252
16:11:31.867 [GPU legend.game.scripting.ScriptManager:135] ERROR:   1: script[12].storage[0] 12
16:11:31.867 [GPU legend.game.scripting.ScriptManager:135] ERROR:   2: script[0x158d] 0x1
16:11:31.868 [GPU legend.game.scripting.ScriptManager:135] ERROR:   3: script[0x158f] 0xfffff800
16:11:31.868 [GPU legend.game.scripting.ScriptManager:138] ERROR: Storage:
16:11:31.868 [GPU legend.game.scripting.ScriptManager:140] ERROR:   1: 0xc
16:11:31.868 [GPU legend.game.scripting.ScriptManager:140] ERROR:   2: 0xffffffff
16:11:31.868 [GPU legend.game.scripting.ScriptManager:140] ERROR:   3: 0xffffffff
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   4: 0xffffffff
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   5: 0xffffffff
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   6: 0xffffffff
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   7: 0xffffffff
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   8: 0x10000
16:11:31.869 [GPU legend.game.scripting.ScriptManager:140] ERROR:   9: 0xffffffff
16:11:31.870 [GPU legend.game.scripting.ScriptManager:140] ERROR:   10: 0xffffffff
16:11:31.870 [GPU legend.game.scripting.ScriptManager:140] ERROR:   11: 0x80
16:11:31.870 [GPU legend.game.scripting.ScriptManager:140] ERROR:   12: 0x80
16:11:31.870 [GPU legend.game.scripting.ScriptManager:140] ERROR:   13: 0x80
16:11:31.870 [GPU legend.game.scripting.ScriptManager:140] ERROR:   14: 0xffffffff
16:11:31.871 [GPU legend.game.scripting.ScriptManager:140] ERROR:   15: 0xffffffff
16:11:31.871 [GPU legend.game.scripting.ScriptManager:140] ERROR:   16: 0xffffffff
16:11:31.871 [GPU legend.game.scripting.ScriptManager:140] ERROR:   17: 0xffffffff
16:11:31.871 [GPU legend.game.scripting.ScriptManager:140] ERROR:   18: 0xffffffff
16:11:31.871 [GPU legend.game.scripting.ScriptManager:140] ERROR:   19: 0xffffffff
16:11:31.872 [GPU legend.game.scripting.ScriptManager:140] ERROR:   20: 0xffffffff
16:11:31.872 [GPU legend.game.scripting.ScriptManager:140] ERROR:   21: 0xffffffff
16:11:31.872 [GPU legend.game.scripting.ScriptManager:140] ERROR:   22: 0xffffffff
16:11:31.872 [GPU legend.game.scripting.ScriptManager:140] ERROR:   23: 0xffffffff
16:11:31.872 [GPU legend.game.scripting.ScriptManager:140] ERROR:   24: 0xffffffff
16:11:31.873 [GPU legend.game.scripting.ScriptManager:140] ERROR:   25: 0xffffffff
16:11:31.873 [GPU legend.game.scripting.ScriptManager:140] ERROR:   26: 0x0
16:11:31.873 [GPU legend.game.scripting.ScriptManager:140] ERROR:   27: 0x0
16:11:31.873 [GPU legend.game.scripting.ScriptManager:140] ERROR:   28: 0x0
16:11:31.873 [GPU legend.game.scripting.ScriptManager:140] ERROR:   29: 0x0
16:11:31.874 [GPU legend.game.scripting.ScriptManager:140] ERROR:   30: 0x0
16:11:31.874 [GPU legend.game.scripting.ScriptManager:140] ERROR:   31: 0x0
16:11:31.874 [GPU legend.game.scripting.ScriptManager:140] ERROR:   32: 0x0
16:11:31.874 [GPU legend.game.scripting.ScriptManager:140] ERROR:   33: 0x0
16:11:31.874 [GPU legend.game.scripting.ScriptManager:143] ERROR: Call stack:
16:11:31.875 [GPU legend.game.scripting.ScriptManager:149] ERROR:   1: 0
16:11:31.875 [GPU legend.game.scripting.ScriptManager:149] ERROR:   2: 0
16:11:31.875 [GPU legend.game.scripting.ScriptManager:149] ERROR:   3: 0
16:11:31.875 [GPU legend.game.scripting.ScriptManager:149] ERROR:   4: 0
16:11:31.875 [GPU legend.game.scripting.ScriptManager:149] ERROR:   5: 0
16:11:31.876 [GPU legend.game.scripting.ScriptManager:149] ERROR:   6: 0
16:11:31.876 [GPU legend.game.scripting.ScriptManager:149] ERROR:   7: 0
16:11:31.876 [GPU legend.game.scripting.ScriptManager:149] ERROR:   8: 0
16:11:31.876 [GPU legend.game.scripting.ScriptManager:149] ERROR:   9: 0
16:11:31.876 [GPU legend.game.scripting.ScriptManager:149] ERROR:   10: 0
16:11:31.879 [GPU legend.core.gpu.Gpu:426] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 12
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:152)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:781)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:707)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$7(Gpu.java:473)
        at legend.core.gpu.Gpu.lambda$run$6(Gpu.java:387)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:518)
        at legend.core.opengl.Window.run(Window.java:258)
        at legend.core.gpu.Gpu.run(Gpu.java:424)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: Cannot cast legend.game.combat.types.BttlScriptData6cSub34 to legend.game.combat.types.BttlScriptData6cSub1c
        at java.base/java.lang.Class.cast(Class.java:3889)
        at legend.core.memory.types.Pointer.derefNullableAs(Pointer.java:105)
        at legend.game.combat.Bttl_800e.FUN_800eaf54(Bttl_800e.java:2725)
        at legend.game.combat.Bttl_800e.FUN_800eb280(Bttl_800e.java:2807)
        at legend.game.combat.Bttl_800e.FUN_800eb48c(Bttl_800e.java:2875)
        at legend.game.combat.Bttl_800e.FUN_800eb518(Bttl_800e.java:2880)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:898)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:534)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:462)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:126)
        ... 10 more

**Comment by DrewUniverse** [comment]
[100.zip](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/10748371/100.zip)
