### ISSUE TITLE
Crash on Fruegel and Doel Cutscene

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#258]
On main.tmd branch. After beating the two bosses the cutscene will produce this crash.

with No Dart on
17:32:37.611 [GPU legend.core.gpu.Gpu:461] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 15
    at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:152)
    at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
    at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:779)
    at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:705)
    at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:508)
    at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:422)
    at legend.core.opengl.Context.draw(Context.java:91)
    at legend.core.opengl.Window$Events.onDraw(Window.java:518)
    at legend.core.opengl.Window.run(Window.java:258)
    at legend.core.gpu.Gpu.run(Gpu.java:459)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
    at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:672)
    at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:730)
    at legend.game.combat.Bttl_800c.FUN_800ca100(Bttl_800c.java:1981)
    at legend.game.combat.Bttl_800c.FUN_800cb84c(Bttl_800c.java:2649)
    at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:898)
    at legend.game.scripting.ScriptState.runOp(ScriptState.java:534)
    at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:462)
    at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:126)
    ... 10 more
    
    
 with Dart
 17:36:10.268 [GPU legend.core.gpu.Gpu:461] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    at legend.game.tmd.Renderer.renderTmdPrimitive(Renderer.java:172)
    at legend.game.tmd.Renderer.renderDobj2(Renderer.java:33)
    at legend.game.combat.Bttl_800d.FUN_800de3f4(Bttl_800d.java:4884)
    at legend.game.combat.SEffe.renderGuardHealEffect(SEffe.java:9633)
    at legend.game.scripting.ScriptState.render(ScriptState.java:184)
    at legend.game.scripting.ScriptManager.executeScriptRenderers(ScriptManager.java:193)
    at legend.game.scripting.ScriptManager.tick(ScriptManager.java:26)
    at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:779)
    at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:705)
    at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:508)
    at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:422)
    at legend.core.opengl.Context.draw(Context.java:91)
    at legend.core.opengl.Window$Events.onDraw(Window.java:518)
    at legend.core.opengl.Window.run(Window.java:258)
    at legend.core.gpu.Gpu.run(Gpu.java:459)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
There's some _very_ weird stuff going on here. Gonna need a lot of investigation. There are a bunch of completely broken TMDs, but it seems the vertices in those might be used for transformations or something like that? Yet another kind of animation file...?

**Comment by LordMonoxide** [comment]
Resolved, it was indeed a sixth type of animation file
