### ISSUE TITLE
Coolon Cutscene Crash

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#292]
Crash getting on Coolon after signet

java.lang.IndexOutOfBoundsException: Read end 32800 out of bounds 32788
	at legend.game.unpacker.FileData.checkBounds(FileData.java:127)
	at legend.game.unpacker.FileData.slice(FileData.java:29)
	at legend.game.types.TmdAnimationFile.<init>(TmdAnimationFile.java:28)
	at legend.game.SMap.executeSceneGraphicsLoadingStage(SMap.java:2695)
	at legend.game.SMap.executeSmapLoadingStage_2(SMap.java:4352)
	at legend.game.SMap.executeSmapLoadingStage(SMap.java:4201)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
	at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:795)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:722)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:508)
	at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:422)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:459)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
Map ID 707
