### ISSUE TITLE
Real Faust fight

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#327]
After a little when entering battle to Faust, a crash happened:
11:39:02.124 [GPU legend.core.gpu.Gpu:445] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 6
    at legend.game.combat.Bttl_800e.FUN_800ec258(Bttl_800e.java:3144)
    at legend.game.combat.Bttl_800e.renderBttlModel(Bttl_800e.java:3354)
    at legend.game.Scus94491BpeSegment_8002.renderModel(Scus94491BpeSegment_8002.java:626)
    at legend.game.combat.Bttl_800c.FUN_800cb024(Bttl_800c.java:2457)
    at legend.game.scripting.ScriptState.render(ScriptState.java:180)
    at legend.game.scripting.ScriptManager.executeScriptRenderers(ScriptManager.java:192)
    at legend.game.scripting.ScriptManager.tick(ScriptManager.java:26)
    at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:570)
    at legend.game.Scus94491BpeSegment.lambda$gameLoop$40(Scus94491BpeSegment.java:496)
    at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:492)
    at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:427)
    at legend.core.opengl.Context.draw(Context.java:91)
    at legend.core.opengl.Window$Events.onDraw(Window.java:600)
    at legend.core.opengl.Window.run(Window.java:267)
    at legend.core.gpu.Gpu.run(Gpu.java:443)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by theflyingzamboni** [comment]
Can be reliably reproduced by throwing a Power Down at Faust.
