### ISSUE TITLE
Crash: Random Battle (Magic Sig Stone??)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#362]
```16:27:24.194 [GPU legend.game.combat.Bttl_800e:999] INFO : Allocated DEFF script state 13
16:27:24.194 [GPU legend.game.Scus94491BpeSegment:982] INFO : Loading support overlay 3
16:27:24.194 [GPU legend.game.Scus94491BpeSegment:1478] INFO : Loading DRGN0 dir 4387 from legend.game.combat.Bttl_800e.loadSpellItemDeff(Bttl_800e.java:1081)
16:27:24.194 [GPU legend.game.unpacker.Unpacker:115] INFO : Loading directory SECT/DRGN0.BIN/4387
16:27:24.195 [GPU legend.game.scripting.ScriptManager:129] ERROR: Script 7 crashed!
16:27:24.195 [GPU legend.game.scripting.ScriptManager:130] ERROR: File S_BTLD BPE @ 800fb77c[2744]
16:27:24.195 [GPU legend.game.scripting.ScriptManager:131] ERROR: Parameters:
16:27:24.195 [GPU legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x26f
16:27:24.195 [GPU legend.game.scripting.ScriptManager:134] ERROR:   1: script[7].storage[8] 232
16:27:24.195 [GPU legend.game.scripting.ScriptManager:134] ERROR:   2: script[7].storage[0] 7
16:27:24.195 [GPU legend.game.scripting.ScriptManager:134] ERROR:   3: script[7].storage[28] 12
16:27:24.195 [GPU legend.game.scripting.ScriptManager:134] ERROR:   4: script[0x993] 0x0
16:27:24.195 [GPU legend.game.scripting.ScriptManager:134] ERROR:   5: script[0x995] 0x2000000
16:27:24.196 [GPU legend.game.scripting.ScriptManager:137] ERROR: Storage:
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   1: 0x7
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   8: 0x10008
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   9: 0xe8
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   10: 0x85
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   11: 0x8
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   12: 0x1f4
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   18: 0x1f
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
16:27:24.196 [GPU legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   24: 0x0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   25: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   26: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   27: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   28: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   29: 0xc
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   30: 0x28
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   31: 0x7
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   32: 0x0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
16:27:24.197 [GPU legend.game.scripting.ScriptManager:142] ERROR: Call stack:
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   1: 13059
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   2: 12510
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   3: 12377
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   4: 0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   5: 0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   6: 0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   7: 0
16:27:24.197 [GPU legend.game.scripting.ScriptManager:148] ERROR:   8: 0
16:27:24.197 [GPU legend.core.gpu.Gpu:453] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 7
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:570)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:496)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:500)
        at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:438)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:600)
        at legend.core.opengl.Window.run(Window.java:267)
        at legend.core.gpu.Gpu.run(Gpu.java:451)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Failed to load directory SECT/DRGN0.BIN/4387
        at legend.game.unpacker.Unpacker.loadDirectory(Unpacker.java:208)
        at legend.game.Scus94491BpeSegment.loadDrgnDir(Scus94491BpeSegment.java:1480)
        at legend.game.combat.Bttl_800e.loadSpellItemDeff(Bttl_800e.java:1081)
        at legend.game.combat.Bttl_800e.scriptLoadDeff(Bttl_800e.java:1446)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:894)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:530)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:458)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 10 more
Caused by: java.nio.file.NoSuchFileException: .\files\SECT\DRGN0.BIN\4387
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
        at legend.game.unpacker.Unpacker.loadDirectory(Unpacker.java:183)
        ... 17 more

**Comment by LordMonoxide** [comment]
This was resolved several minutes before the issue was posted
