### ISSUE TITLE
Crash in Aglis doing nothing special

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#388]
21:40:13.243 [GPU legend.core.gpu.Gpu:453] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at legend.game.Scus94491BpeSegment_8002.animateModel(Scus94491BpeSegment_8002.java:509)
	at legend.game.combat.Bttl_800c.FUN_800cafb4(Bttl_800c.java:2432)
	at legend.game.scripting.ScriptState.tick(ScriptState.java:166)
	at legend.game.scripting.ScriptManager.executeScriptTickers(ScriptManager.java:170)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:24)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:568)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:494)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:500)
	at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:438)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:600)
	at legend.core.opengl.Window.run(Window.java:267)
	at legend.core.gpu.Gpu.run(Gpu.java:451)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by dragoonsouls** [comment]
well was doing a full farming for Meru additions there, cat's cradle and perky step, never get crash there. Since a lot of updates happens between maybe it's solved.
