### ISSUE TITLE
[Crash] "The End" screen

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#422]
```
21:45:38.922 [GPU legend.game.Scus94491BpeSegment_8002:343] INFO : Loading scripted TMD legend.game.types.CContainer@1a734c0c (animation legend.game.types.TmdAnimationFile@3d9ea89)
22:22:05.896 [GPU legend.core.gpu.Gpu:453] ERROR: Shutting down due to GPU exception:
java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
        at legend.game.SMap.FUN_800dde70(SMap.java:1053)
        at legend.game.SMap.FUN_800da114(SMap.java:804)
        at legend.game.Scus94491BpeSegment_8002.animateModel(Scus94491BpeSegment_8002.java:426)
        at legend.game.SMap.FUN_800eece0(SMap.java:7461)
        at legend.game.SMap.FUN_800eddb4(SMap.java:7139)
        at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:448)
        at legend.core.memory.types.RunnableRef.run(RunnableRef.java:18)
        at legend.game.SMap.FUN_800e4708(SMap.java:3728)
        at legend.game.Scus94491BpeSegment_8002.FUN_80020ed8(Scus94491BpeSegment_8002.java:528)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:501)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:500)
        at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:438)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:642)
        at legend.core.opengl.Window.run(Window.java:269)
        at legend.core.gpu.Gpu.run(Gpu.java:451)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
This was caused by a short overflowing
