### ISSUE TITLE
javafx fails to launch but only when compiled

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#460]
```java
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
        at com.sun.javafx.application.PlatformImpl.isFxApplicationThread(PlatformImpl.java:428)
        at com.sun.javafx.application.PlatformImpl.checkIdle(PlatformImpl.java:547)
        at com.sun.javafx.application.PlatformImpl.setImplicitExit(PlatformImpl.java:504)
        at javafx.application.Platform.setImplicitExit(Platform.java:230)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:471)
        at legend.core.opengl.Window$Events.lambda$onKey$3(Window.java:381)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at legend.core.opengl.Window$Events.onKey(Window.java:381)
        at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
        at org.lwjgl.system.JNI.invokeV(Native Method)
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
        at legend.core.opengl.Window.run(Window.java:261)
        at legend.core.gpu.Gpu.run(Gpu.java:450)
        at legend.core.GameEngine.start(GameEngine.java:216)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:833)
23:27:46.186 [Hardware legend.game.Scus94491BpeSegment:474] INFO : Failed to start script debugger
java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
        at com.sun.javafx.application.PlatformImpl.isFxApplicationThread(PlatformImpl.java:428)
        at com.sun.javafx.application.PlatformImpl.checkIdle(PlatformImpl.java:547)
        at com.sun.javafx.application.PlatformImpl.setImplicitExit(PlatformImpl.java:504)
        at javafx.application.Platform.setImplicitExit(Platform.java:230)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:471)
        at legend.core.opengl.Window$Events.lambda$onKey$3(Window.java:381)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at legend.core.opengl.Window$Events.onKey(Window.java:381)
        at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
        at org.lwjgl.system.JNI.invokeV(Native Method)
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
        at legend.core.opengl.Window.run(Window.java:261)
        at legend.core.gpu.Gpu.run(Gpu.java:450)
        at legend.core.GameEngine.start(GameEngine.java:216)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
```

**Comment by LordMonoxide** [comment]
![image](https://user-images.githubusercontent.com/437657/235825838-274628fc-18d0-47b2-a338-ef21c26abb37.png)
It's because the linux natives are getting copied in

**Comment by LordMonoxide** [comment]
Looks like there is recent progress on a PR to the javafx plugin to allow platform configuration
https://github.com/openjfx/javafx-gradle-plugin/pull/137
