### ISSUE TITLE
Dragoon addition gets stuck

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#48]
I wasn't able to perform the addition, and then the addition spinner didn't disappear
![image](https://user-images.githubusercontent.com/437657/186543449-9bf2458b-cb29-4c9d-a3ea-eb5c465b3e06.png)

**Comment by LordMonoxide** [comment]
Seems the script is failing to unload too, which crashes the game once combat is unloaded because it's still trying to call the now-unloaded script callbacks

**Comment by LordMonoxide** [comment]
Haven't seen this happen since. Needs further investigation.

**Comment by Voreani** [comment]
This issue appears to be resolved. I performed the addition attack with Dart as dragoon and the game did not crash and the addition counter went away.

**Comment by Zychronix** [comment]
I crashed at the Fruegel 2 battle with the Dragoon Meter still open. 

ERROR Gpu Shutting down due to GPU exception:
 java.lang.UnsupportedOperationException: There is no method at 108574. The value is c0415a3.
        at legend.core.memory.Segment.getFunction(Segment.java:81)
        at legend.core.memory.Memory$MemoryValue.call(Memory.java:414)
        at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
        at legend.game.Scus94491BpeSegment.executeScriptCallbacks1(Scus94491BpeSegment.java:4226)
        at legend.game.Scus94491BpeSegment.executeScripts1(Scus94491BpeSegment.java:2810)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:826)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$42(Scus94491BpeSegment.java:670)
        at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:514)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:346)
        at legend.core.opengl.Window.run(Window.java:225)
        at legend.core.gpu.Gpu.run(Gpu.java:526)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LordMonoxide** [comment]
Yeah just happened to me in a regular fight too. I loaded a saved state where Haschel was already transformed. Had you also loaded a saved state where the character was already transformed @Zychronix?

**Comment by LordMonoxide** [comment]
I was playing last night and every time I tried to use Haschel's D-attack it did this
