### ISSUE TITLE
Crash on Disk 2 fight

### ISSUE THREAD

**Issue by greenbrettmichael** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#517]
Crashed on random disk 2 fight while attacking enemy with a normal attack. Crash happened right before enemy defeat after addition. log attached:
full log:
https://pastebin.com/eKGanndC
error section:
17:13:57.172 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 18 crashed!
17:13:57.172 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 4632/1[5328]
17:13:57.172 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
17:13:57.173 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x349
17:13:57.173 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[18].storage[0] 18
17:13:57.173 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[0x14e0] 0x8
17:13:57.173 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
17:13:57.173 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0x12
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x10000
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0xffffffff
17:13:57.174 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0x11
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0xfffff545
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xfffffc63
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0x7d3
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
17:13:57.175 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   9: 0
17:13:57.176 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   10: 0
17:13:57.176 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 18
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:595)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:521)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:635)
        at legend.core.opengl.Window.run(Window.java:262)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:216)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: legend.core.memory.MisalignedAccessException: Misaligned memory access at address 808f3052 for size 4
        at legend.core.memory.Memory.checkAlignment(Memory.java:80)
        at legend.core.memory.Memory.ref(Memory.java:248)
        at legend.core.memory.Memory$MemoryValue.offset(Memory.java:351)
        at legend.core.memory.types.UnboundedArrayRef.lambda$get$2(UnboundedArrayRef.java:46)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:454)
        at legend.core.memory.types.UnboundedArrayRef.get(UnboundedArrayRef.java:46)
        at legend.game.combat.SEffe.FUN_80105c38(SEffe.java:3522)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:894)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:530)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:458)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 12 more

**Comment by greenbrettmichael** [comment]
Arrow Shooter
https://legendofdragoon.fandom.com/wiki/Arrow_Shooter

**Comment by theflyingzamboni** [comment]
Do you recall who was attacking and what they were equipped with?

**Comment by greenbrettmichael** [comment]
the addition used was "crush dance" auto additions was on
