### ISSUE TITLE
Game crash if trying to select no equipment

### ISSUE THREAD

**Issue by MaximeMaillot** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#651]
On Windows, using : Severed Chains Recommended Build #2 + Hard Mode Preview Release 14

Crash log :
```
[Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at legend.game.inventory.screens.EquipmentScreen.menuSelect(EquipmentScreen.java:298)
        at legend.game.inventory.screens.EquipmentScreen.pressedThisFrame(EquipmentScreen.java:342)
        at legend.game.inventory.screens.MenuStack.lambda$pressedThisFrame$5(MenuStack.java:214)
        at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:107)
        at legend.game.inventory.screens.MenuStack.input(MenuStack.java:99)
        at legend.game.inventory.screens.MenuStack.pressedThisFrame(MenuStack.java:214)
        at legend.core.opengl.Window$Events.lambda$onInputPressedThisFrame$11(Window.java:440)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at legend.core.opengl.Window$Events.onInputPressedThisFrame(Window.java:440)
        at legend.core.opengl.Window$Events.callInputEvents(Window.java:459)
        at legend.game.input.Input.update(Input.java:68)
        at legend.core.opengl.Window.tickInput(Window.java:289)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
```
  
How it happens : 
Menu => Equipment => Enter on an empty slot (no equipment)
<img width="1921" alt="java_9C7XTq06VF" src="https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/25479622/6ab81a30-6e7b-4e68-8af6-778cba1e330f">

**Comment by LordMonoxide** [comment]
Ah, I think I see the issue here, there's a check to see if the equipment index is less than your total equipment count, but it doesn't factor in what equipment a character can equip
