### ISSUE TITLE
Sound thread crashes when entering battle at high FPS

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#661]
```
13:53:13.787 [Thread-2 legend.game.Scus94491BpeSegment:480] ERROR: Sound thread crashed!
java.lang.UnsupportedOperationException
    at legend.game.sound.SssqReader.baseVolume(SssqReader.java:9)
    at legend.game.sound.Sequencer.handleVolumeChanging(Sequencer.java:2009)
    at legend.game.sound.Sequencer.tick(Sequencer.java:172)
    at legend.game.Scus94491BpeSegment.soundLoop(Scus94491BpeSegment.java:478)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

Consistently get error when entering battle with Kanzas with FPS limit set to 240FPS. Sound thread seems to crash during the start-up animations.

**Comment by LordMonoxide** [comment]
Closing in favour of #722 which has slightly more info
