### ISSUE TITLE
Crash while using Frozen Jet on main

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#690]
13:33:46.003 [Hardware legend.game.combat.Bttl_800e:1594] INFO : Deallocating effect manager 19
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 12 crashed!
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 4410/1[3167]
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x249
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[12].storage[19] 17
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   2: script[0xc86] 0x1
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   3: script[0xc87] 0x14
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   4: script[0xc89] 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xc
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x90000
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0x1
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0x1
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0x12
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
13:33:48.403 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0x14
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xd
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xe
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0x10
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0x11
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0x15
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0x16
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0x13
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0xb
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0x6
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0xffffffff
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
13:33:48.404 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
13:33:48.404 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 12
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:436)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:174)
	at legend.core.opengl.Window$Events.onDraw(Window.java:671)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:228)
	at legend.game.Main.main(Main.java:23)
Caused by: java.lang.ClassCastException: class legend.game.combat.effects.EffectManagerData6cInner$FrozenJetType cannot be cast to class legend.game.combat.effects.EffectManagerData6cInner$AnimType (legend.game.combat.effects.EffectManagerData6cInner$FrozenJetType and legend.game.combat.effects.EffectManagerData6cInner$AnimType are in unnamed module of loader 'app')
	at legend.game.combat.SEffe.FUN_80114f3c(SEffe.java:8013)
	at legend.game.combat.SEffe.FUN_80115014(SEffe.java:8049)
	at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:906)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:542)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:470)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
	... 11 more
13:33:48.405 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...

**Comment by Zychronix** [comment]
Michael shadow explosion crash
22:54:56.913 [Hardware legend.game.combat.Bttl_800e:1669] INFO : Allocating empty effect manager 31 (parent: 23) from legend.game.combat.Bttl_800e.allocateEffectManager(Bttl_800e.java:1645)
22:54:56.913 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 23 crashed!
22:54:56.913 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File 5388/1[2642]
22:54:56.913 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
22:54:56.913 [Hardware legend.game.scripting.ScriptManager:132] ERROR: Op param: 0x229
22:54:56.913 [Hardware legend.game.scripting.ScriptManager:134] ERROR: 1: script[23].storage[18] 31
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:134] ERROR: 2: script[0xa7a] 0x0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:134] ERROR: 3: script[0xa7b] 0xf
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 1: 0x17
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 2: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 3: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 4: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 5: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 6: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 7: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 8: 0x90000
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 9: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 10: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 11: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 12: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 13: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 14: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 15: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 16: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 17: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 18: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 19: 0x1f
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 20: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 21: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 22: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 23: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 24: 0x0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 25: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 26: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 27: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 28: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 29: 0x6
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 30: 0x13
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 31: 0xb
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 32: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:139] ERROR: 33: 0xffffffff
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 1: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 2: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 3: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 4: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 5: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 6: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 7: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 8: 0
22:54:56.914 [Hardware legend.game.scripting.ScriptManager:148] ERROR: 9: 0
22:54:56.914 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 23
at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:436)
at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:174)
at legend.core.opengl.Window$Events.onDraw(Window.java:671)
at legend.core.opengl.Window.tickFrame(Window.java:312)
at legend.core.opengl.Action.run(Action.java:46)
at legend.core.opengl.Action.tick(Action.java:32)
at legend.core.opengl.Window.run(Window.java:289)
at legend.core.RenderEngine.run(RenderEngine.java:246)
at legend.core.GameEngine.start(GameEngine.java:228)
at legend.game.Main.main(Main.java:23)
Caused by: java.lang.IllegalArgumentException: Invalid index 0
at legend.game.combat.effects.EffectManagerData6cInner$VoidType.set24(EffectManagerData6cInner.java:344)
at legend.game.combat.SEffe.FUN_80114e60(SEffe.java:7998)
at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:906)
at legend.game.scripting.ScriptState.runOp(ScriptState.java:542)
at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:470)
at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
... 11 more
22:54:56.916 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...
