### ISSUE TITLE
Crash detected, Message: Failed to locate library: lwjgl.dll

### ISSUE THREAD

**Issue by BigheadSMZ** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#705]
So I just found this project today and decided to give it a go. I added my disc images to the "isos" folder and tried "launch.bat". It looked like it downloaded some java stuff, then immediately after I get an error message.

17:52:17.604 [Hardware legend.game.Main:28] ERROR: ----------------------------------------------------------------------------
17:52:17.604 [Hardware legend.game.Main:29] ERROR: Crash detected
17:52:17.605 [Hardware legend.game.Main:32] ERROR: Message: Failed to locate library: lwjgl.dll
17:52:17.605 [Hardware legend.game.Main:35] ERROR: ----------------------------------------------------------------------------
17:52:17.605 [Hardware legend.game.Main:36] ERROR: Stack trace:
java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
        at org.lwjgl.system.Library.loadSystem(Library.java:174)
        at org.lwjgl.system.Library.loadSystem(Library.java:64)
        at org.lwjgl.system.Library.<clinit>(Library.java:52)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
        at legend.core.opengl.Window.<clinit>(Window.java:85)
        at legend.core.gpu.Gpu.init(Gpu.java:158)
        at legend.core.gpu.Gpu.run(Gpu.java:138)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
17:52:17.606 [Hardware legend.game.Main:37] ERROR: Press any key to shut down...

Is there something I'm missing? There isn't much information that I can find anywhere in how to properly set this up. Is there a dependency I'm missing? A quick Google search of the missing file brings up a bunch of ambiguous information that does not help me get any closer to figuring out the solution.

**Comment by BigheadSMZ** [comment]
Nevermind, apparently I'm dyslexic. I read the download as "AMD64" when its actually "ARM64". Not one of my prouder moments...
