### ISSUE TITLE
Starting a new campaign after quitting the game causes a crash

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#714]
On destatic branch

java.lang.NullPointerException: Cannot invoke "legend.game.types.UiFile.uiElements_0000()" because "legend.game.Scus94491BpeSegment_800b.uiFile_800bdc3c" is null
	at legend.game.Scus94491BpeSegment_8002.allocateManualRenderable(Scus94491BpeSegment_8002.java:1446)
	at legend.game.inventory.screens.controls.Background.<init>(Background.java:19)
	at legend.game.inventory.screens.SaveGameScreen.<init>(SaveGameScreen.java:40)
	at legend.game.inventory.screens.MainMenuScreen.showSaveScreen(MainMenuScreen.java:295)
	at legend.game.inventory.screens.MainMenuScreen.lambda$addButton$6(MainMenuScreen.java:146)
	at legend.game.inventory.screens.Control.pressedWithRepeatPulse(Control.java:402)
	at legend.game.inventory.screens.MenuScreen.pressedWithRepeatPulse(MenuScreen.java:140)
	at legend.game.inventory.screens.MenuStack.lambda$pressedWithRepeatPulse$7(MenuStack.java:223)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:100)
	at legend.game.inventory.screens.MenuStack.pressedWithRepeatPulse(MenuStack.java:223)
	at legend.core.opengl.Window$Events.lambda$onInputPressedWithRepeat$13(Window.java:470)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at legend.core.opengl.Window$Events.onInputPressedWithRepeat(Window.java:470)
	at legend.core.opengl.Window$Events.callInputEvents(Window.java:478)
	at legend.game.input.Input.update(Input.java:63)
	at legend.core.opengl.Window.tickInput(Window.java:307)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
20:34:36.752 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...

**Comment by LordMonoxide** [comment]
No longer happening
