### ISSUE TITLE
Shop Menu Crashes/Bugs

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#719]
On destatic branch

When on the shop menu and using a mouse clicking on a blank spot will crash the game

22:24:47.064 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at legend.game.inventory.screens.ShopScreen.mouseClick(ShopScreen.java:595)
	at legend.game.inventory.screens.MenuStack.lambda$mouseRelease$2(MenuStack.java:191)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:108)
	at legend.game.inventory.screens.MenuStack.input(MenuStack.java:100)
	at legend.game.inventory.screens.MenuStack.mouseRelease(MenuStack.java:191)
	at legend.core.opengl.Window$Events.lambda$onMouseButton$9(Window.java:445)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at legend.core.opengl.Window$Events.onMouseButton(Window.java:445)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at legend.core.opengl.Window.tickInput(Window.java:306)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
22:24:47.065 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...

**Comment by Zychronix** [comment]
Shop items are sometimes duplicated but reopening the shop fixes it sometimes
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/c67176b5-8ef3-4263-938c-2a700b34051a)
