### ISSUE TITLE
Monster Battle Crashes

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#725]
Sandora Elite (the first one in Hoax) crashes when it is using one of its attacks.
This does not happen all the time and the battle can be completed most of the time.

13:23:48.480 [Hardware legend.game.combat.Bttl_800e:1829] INFO : Allocating effect manager 15 for ModelEffect13c (parent: 14) from legend.game.combat.Bttl_800e.FUN_800e9f68(Bttl_800e.java:2316)
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:153] ERROR: Script 14 crashed!
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:154] ERROR: File 4954/1[addr 0x18a4]
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:155] ERROR: Parameters:
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:156] ERROR:   Op param: 0x23e
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   1: script[14].storage[29] 15
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   2: script[0x644] 0x10201
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:161] ERROR: Storage:
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   1: 0xe
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   2: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   3: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   4: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   5: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   6: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   7: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   8: 0x90000
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   9: 0x6
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   10: 0x7
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   11: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   12: 0x6
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   13: 0x7
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   14: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   15: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   16: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   17: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   18: 0xb
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   19: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   20: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   21: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   22: 0xa00
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   23: 0x0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   24: 0xfffffc00
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   25: 0xa00
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   26: 0x0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   27: 0x400
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   28: 0xb
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   29: 0x7
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   30: 0xf
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   31: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   32: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   33: 0xffffffff
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:166] ERROR: Call stack:
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   1: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   2: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   3: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   4: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   5: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   6: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   7: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   8: 0
13:23:48.481 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   9: 0
13:23:48.481 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 14
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:175)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:424)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:174)
	at legend.core.opengl.Window$Events.onDraw(Window.java:671)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
	at legend.game.combat.Bttl_800e.getDeffPart(Bttl_800e.java:2648)
	at legend.game.combat.SEffe.scriptLoadEffectModelAnimation(SEffe.java:9962)
	at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:925)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:552)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:480)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:149)
	... 11 more
13:23:48.483 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...
13:23:48.488 [pool-2-thread-13 legend.game.combat.Bttl_800e:1436] INFO : Loading DEFF files
13:23:48.489 [pool-2-thread-13 legend.game.unpacker.Unpacker:179] INFO : Directory SECT/DRGN0.BIN/4954/0 loaded (remaining queued: 1)
13:23:48.500 [pool-2-thread-30 legend.game.combat.Bttl_800e:2028] INFO : Loading DEFF TIMs
13:23:48.500 [pool-2-thread-30 legend.game.unpacker.Unpacker:179] INFO : Directory SECT/DRGN0.BIN/4953 loaded (remaining queued: 0)

**Comment by Zychronix** [comment]
Fire Bird crash
14:30:14.130 [Hardware legend.game.combat.Bttl_800e:1829] INFO : Allocating effect manager 21 for ModelEffect13c (parent: 17) from legend.game.combat.Bttl_800e.FUN_800e9f68(Bttl_800e.java:2316)
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:153] ERROR: Script 17 crashed!
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:154] ERROR: File 5220/1[addr 0x1f18]
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:155] ERROR: Parameters:
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:156] ERROR:   Op param: 0x23e
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   1: script[17].storage[18] 21
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   2: script[17].storage[8] 85249
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:161] ERROR: Storage:
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   1: 0x11
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   2: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   3: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   4: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   5: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   6: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   7: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   8: 0x90000
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   9: 0x14d01
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   10: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   11: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   12: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   13: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   14: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   15: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   16: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   17: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   18: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   19: 0x15
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   20: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   21: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   22: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   23: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   24: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   25: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   26: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   27: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   28: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   29: 0x6
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   30: 0x0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   31: 0xb
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   32: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   33: 0xffffffff
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:166] ERROR: Call stack:
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   1: 2005
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   2: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   3: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   4: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   5: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   6: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   7: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   8: 0
14:30:14.130 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   9: 0
14:30:14.131 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 17
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:175)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:424)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:174)
	at legend.core.opengl.Window$Events.onDraw(Window.java:671)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
	at legend.game.combat.Bttl_800e.getDeffPart(Bttl_800e.java:2648)
	at legend.game.combat.SEffe.scriptLoadEffectModelAnimation(SEffe.java:9962)
	at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:925)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:552)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:480)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:149)
	... 11 more
14:30:14.132 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...
14:30:14.161 [pool-2-thread-17 legend.game.combat.Bttl_800e:1436] INFO : Loading DEFF files
14:30:14.161 [pool-2-thread-17 legend.game.unpacker.Unpacker:179] INFO : Directory SECT/DRGN0.BIN/5220/0 loaded (remaining queued: 1)
14:30:14.161 [pool-2-thread-27 legend.game.combat.Bttl_800e:2028] INFO : Loading DEFF TIMs
14:30:14.161 [pool-2-thread-27 legend.game.unpacker.Unpacker:179] INFO : Directory SECT/DRGN0.BIN/5219 loaded (remaining queued: 0)
