### ISSUE TITLE
Overflow items not appearing on replacement screen

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#726]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/5534bfee-1399-4509-a2cd-b857f8c63b7c)

The replaced item description does not update.

**Comment by Zychronix** [comment]
Multiple items in the replace menu causes a crash when trying to select more or possibly it's loopback menu code that is not working?

13:45:30.321 [Hardware legend.core.RenderEngine:248] ERROR: Shutting down due to exception:
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at legend.game.inventory.screens.TooManyItemsScreen.render(TooManyItemsScreen.java:118)
	at legend.game.inventory.screens.MenuScreen.renderScreen(MenuScreen.java:68)
	at legend.game.inventory.screens.MenuStack.propagate(MenuStack.java:117)
	at legend.game.inventory.screens.MenuStack.render(MenuStack.java:89)
	at legend.game.SItem.renderPostCombatReport(SItem.java:2164)
	at legend.game.Scus94491BpeSegment_8002.loadAndRenderMenus(Scus94491BpeSegment_8002.java:989)
	at legend.game.Scus94491BpeSegment.renderPostCombatScreen(Scus94491BpeSegment.java:1242)
	at legend.game.combat.Battle.tick(Battle.java:25)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:419)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:174)
	at legend.core.opengl.Window$Events.onDraw(Window.java:671)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:246)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
13:45:30.323 [Hardware legend.core.opengl.Window:99] INFO : Shutting down...

**Comment by LordMonoxide** [comment]
Fixed in f1d94bb6
