### ISSUE TITLE
Repeated zoom crash

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#766]
Happens if you zoom out and in a couple times on the world map
```java
java.lang.IllegalArgumentException: Overflow: 8192
	at legend.core.memory.types.UnsignedByteRef.set(UnsignedByteRef.java:35)
	at legend.core.gte.COLOUR.setR(COLOUR.java:50)
	at legend.game.wmap.WMap.updateLights(WMap.java:1686)
	at legend.game.wmap.WMap.updateMapCameraAndLights(WMap.java:1631)
	at legend.game.wmap.WMap.handleAndRenderMapAndPlayer(WMap.java:777)
	at legend.game.wmap.WMap.handleAndRenderWmap(WMap.java:651)
	at legend.game.wmap.WMap.tick(WMap.java:481)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:418)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:338)
	at legend.core.opengl.Window$Events.onDraw(Window.java:670)
	at legend.core.opengl.Window.tickFrame(Window.java:311)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:288)
	at legend.core.RenderEngine.run(RenderEngine.java:635)
	at legend.core.GameEngine.start(GameEngine.java:230)
	at legend.game.Main.main(Main.java:23)
```

**Comment by theflyingzamboni** [comment]
Fixed by 52c2608c89ffdd3ddead82f9f1e4095fa4ccf423
