### ISSUE TITLE
[Recommended Build #2 Hotfix 1] - Out of bounds exception when interacting with npc on edge of map. 

### ISSUE THREAD

**Issue by TheDarkestDarkness** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#836]
An issue was experienced when trying to interact with a character on the edge of the map from a certain angle. 
The UI crashes and closes but the music still plays in the background, after the exception occurs the game has to be closed out and restarted.

I am not sure if this only occurs in this area or if this is a known issue. 
I would suspect that this could cause problems at any time when interacting with things on the edge of the screen.

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/16749123/df03b5d5-fac1-4a14-a221-41e630119ccc)

--> original exception <--
00:12:46.543 [Hardware legend.game.scripting.ScriptState:260] INFO : Forking script 14 to 26 legend.game.scripting.ScriptState.scriptForkAndReenter(ScriptState.java:1092)
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 14 crashed!
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File Submap object 4 (DRGN1/36/5)[782]
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x61
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[14].storage[0] 14
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
00:12:46.874 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xe
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0x1a
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x210000
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
00:12:46.878 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x0
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0x0
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xff
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xfffff9b5
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0x538
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xffffff6c
00:12:46.884 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xfffffcbc
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0xfffffff1
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0x0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0x0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 1616
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 1090
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   9: 0
00:12:46.895 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   10: 0
00:12:46.895 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 14
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:596)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:514)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:653)
        at legend.core.opengl.Window.tickFrame(Window.java:294)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
        at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:686)
        at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:744)
        at legend.game.SMap.FUN_800dfec8(SMap.java:1904)
        at legend.game.SMap.FUN_800df198(SMap.java:1503)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:904)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:540)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:468)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 15 more
00:12:46.905 [Hardware legend.core.opengl.Window:93] INFO : Shutting down...

--> Reproduced Exception <--
00:35:24.616 [Hardware legend.game.scripting.ScriptState:260] INFO : Forking script 14 to 26 legend.game.scripting.ScriptState.scriptForkAndReenter(ScriptState.java:1092)
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:129] ERROR: Script 14 crashed!
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:130] ERROR: File Submap object 4 (DRGN1/36/5)[782]
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:131] ERROR: Parameters:
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:132] ERROR:   Op param: 0x61
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:134] ERROR:   1: script[14].storage[0] 14
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:137] ERROR: Storage:
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   1: 0xe
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   2: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   3: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   4: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   5: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   6: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   7: 0x1a
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   8: 0x210000
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   9: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   10: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   11: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   12: 0xffffffff
00:35:24.947 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   13: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   14: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   15: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   16: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   17: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   18: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   19: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   20: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   21: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   22: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   23: 0xffffffff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   24: 0x0
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   25: 0x0
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   26: 0xff
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   27: 0xfffffea3
00:35:24.958 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   28: 0x0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   29: 0xffffff6c
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   30: 0xfffffcbc
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   31: 0xfffffff1
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   32: 0x0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:139] ERROR:   33: 0x0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:142] ERROR: Call stack:
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   1: 1616
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   2: 1093
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   3: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   4: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   5: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   6: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   7: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   8: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   9: 0
00:35:24.969 [Hardware legend.game.scripting.ScriptManager:148] ERROR:   10: 0
00:35:24.969 [Hardware legend.core.gpu.Gpu:148] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 14
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:151)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
        at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:596)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:514)
        at legend.core.gpu.Gpu.lambda$setStandardRenderer$4(Gpu.java:272)
        at legend.core.gpu.Gpu.lambda$init$3(Gpu.java:222)
        at legend.core.opengl.Context.draw(Context.java:91)
        at legend.core.opengl.Window$Events.onDraw(Window.java:653)
        at legend.core.opengl.Window.tickFrame(Window.java:294)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:271)
        at legend.core.gpu.Gpu.run(Gpu.java:146)
        at legend.core.GameEngine.start(GameEngine.java:225)
        at legend.game.Main.main(Main.java:23)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
        at legend.game.Scus94491BpeSegment_8002.applyModelPartTransforms(Scus94491BpeSegment_8002.java:686)
        at legend.game.Scus94491BpeSegment_8002.loadModelStandardAnimation(Scus94491BpeSegment_8002.java:744)
        at legend.game.SMap.FUN_800dfec8(SMap.java:1904)
        at legend.game.SMap.FUN_800df198(SMap.java:1503)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:904)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:540)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:468)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:125)
        ... 15 more
00:35:24.979 [Hardware legend.core.opengl.Window:93] INFO : Shutting down...

**Comment by avionanx** [comment]
Duplicate of #895

**Comment by TheDarkestDarkness** [comment]
Closing this report since it is a duplicate of #813
