### ISSUE TITLE
Shana Star Children Crash

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#89]
When trying to use Start Children in Shana Dragoon form, will result in a crash, no matter the situation, surely a new type of Particle going on...

**Comment by LordMonoxide** [comment]
```
00:02:32.179 [GPU legend.core.gpu.Gpu:557] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: Script subfunc 803 error
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3992)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3598)
	at legend.game.Scus94491BpeSegment.executeScripts1(Scus94491BpeSegment.java:2988)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:1005)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:849)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:519)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: There is no method at 10e04c. The value is 27bdffc0.
	at legend.core.memory.Segment.getFunction(Segment.java:81)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:414)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3990)
	... 15 more
```
