### ISSUE TITLE
Script Crash - RB2.1

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#942]
Script Location DRGN2/402/3 (dragon nest, at weird plant) 

Does not crash on disc1

```23:55:35.122 [Hardware legend.game.scripting.ScriptManager:115] INFO : Allocating script index 15 (Submap object 5 (file 165))
23:55:35.122 [Hardware legend.game.scripting.ScriptState:203] INFO : Loading script Submap object 5 (DRGN2/402/6) into index 15 (entry point 0x0)
23:55:35.122 [Hardware legend.game.Scus94491BpeSegment_8002:315] INFO : Loading scripted TMD legend.game.types.CContainer@1124172b (animation legend.game.types.TmdAnimationFile@554d8d87)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
Allocated SobjModel (index 5)
23:55:35.123 [Hardware legend.game.unpacker.Unpacker:145] INFO : Loading file SUBMAP/alert.tim
23:55:35.125 [Hardware legend.game.scripting.ScriptManager:153] ERROR: Script 12 crashed!
23:55:35.125 [Hardware legend.game.scripting.ScriptManager:154] ERROR: File Submap object 2 (DRGN2/402/3)[addr 0x778]
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:155] ERROR: Parameters:
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:156] ERROR:   Op param: 0x0
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   1: null
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:158] ERROR:   2: null
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:161] ERROR: Storage:
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   1: 0xc
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   2: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   3: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   4: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   5: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   6: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   7: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   8: 0x10000
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   9: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   10: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   11: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   12: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   13: 0xffffffff
23:55:35.126 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   14: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   15: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   16: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   17: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   18: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   19: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   20: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   21: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   22: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   23: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   24: 0x0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   25: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   26: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   27: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   28: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   29: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   30: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   31: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   32: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:163] ERROR:   33: 0xffffffff
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:166] ERROR: Call stack:
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   1: 489
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   2: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   3: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   4: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   5: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   6: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   7: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   8: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   9: 0
23:55:35.127 [Hardware legend.game.scripting.ScriptManager:172] ERROR:   10: 0
23:55:35.128 [Hardware legend.core.RenderEngine:887] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 12
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:175)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:411)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:441)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:885)
	at legend.core.GameEngine.start(GameEngine.java:219)
	at legend.game.Main.main(Main.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1054 out of bounds for length 953
	at legend.game.scripting.ScriptFile.getOp(ScriptFile.java:25)
	at legend.game.scripting.RunningScript.getOp(RunningScript.java:20)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:327)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:149)
	... 11 more
23:55:35.130 [Hardware legend.core.opengl.Window:98] INFO : Shutting down...```

**Comment by LordMonoxide** [comment]
The disk 2 script is missing 102 data entries at the end of the script
