### ISSUE TITLE
Crash when going down the slide in Snowfield. 

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#958]
```18:13:53.965 [Hardware legend.core.RenderEngine:894] ERROR: Shutting down due to exception:
java.lang.NullPointerException: Cannot invoke "legend.core.opengl.Obj.shouldRender(legend.game.types.Translucency)" because "entry.obj" is null
	at legend.core.RenderEngine.renderPool(RenderEngine.java:582)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:470)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:892)
	at legend.core.GameEngine.start(GameEngine.java:219)
	at legend.game.Main.main(Main.java:23)
18:13:53.970 [Hardware legend.core.opengl.Window:98] INFO : Shutting down...

**Comment by LordMonoxide** [comment]
Fixed in 1e0316fe
