### ISSUE TITLE
Crash on entering the cave shelter in Snowfield (Lloyd ushering Dart inside)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#966]
In case it matters, entering the cave went fine before #958 was fixed.

```01:53:23.374 [Hardware legend.core.RenderEngine:894] ERROR: Shutting down due to exception:
java.lang.NullPointerException: Cannot invoke "legend.game.tim.Tim.getImageRect()" because "texture" is null
	at legend.game.submap.SMap.executeSmapLoadingStage_2(SMap.java:4755)
	at legend.game.submap.SMap.tick(SMap.java:4654)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:406)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:442)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:892)
	at legend.core.GameEngine.start(GameEngine.java:219)
	at legend.game.Main.main(Main.java:23)

**Comment by LordMonoxide** [comment]
Resolved with 9e1c112
