### ISSUE TITLE
Haschel - Thunder Kid missing code

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#97]
```
java.lang.UnsupportedOperationException: There is no method at fcf18. The value is 3e00008.
	at legend.core.memory.Segment.getFunction(Segment.java:81)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:414)
	at legend.game.combat.SEffe.FUN_800fd87c(SEffe.java:1401)
	at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.TriConsumerRef.run(TriConsumerRef.java:23)
	at legend.game.Scus94491BpeSegment.executeScriptCallbacks2(Scus94491BpeSegment.java:4449)
	at legend.game.Scus94491BpeSegment.executeScripts2(Scus94491BpeSegment.java:2995)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:1006)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:849)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:519)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
I implemented the unreversed code but there's an actual bug somewhere - -1 is getting passed as the script index when allocating a particle effect manager.
```
23:38:31.262 [GPU legend.core.gpu.Gpu:557] ERROR: Shutting down due to GPU exception:
java.lang.IndexOutOfBoundsException: Index -1 is out of bounds (0 <= n < 72)
	at legend.core.memory.types.ArrayRef.checkIndex(ArrayRef.java:43)
	at legend.core.memory.types.ArrayRef.get(ArrayRef.java:48)
	at legend.game.Scus94491BpeSegment.loadScriptFile(Scus94491BpeSegment.java:3186)
	at legend.game.Scus94491BpeSegment.loadScriptFile(Scus94491BpeSegment.java:3181)
	at legend.game.combat.Bttl_800e.allocateEffectManager(Bttl_800e.java:3434)
	at legend.game.combat.SEffe.FUN_801052dc(SEffe.java:3626)
	at jdk.internal.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.scriptExecuteSubFunc(Scus94491BpeSegment.java:3990)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at legend.core.memory.Memory$MemoryValue.call(Memory.java:425)
	at legend.core.memory.types.FunctionRef.run(FunctionRef.java:25)
	at legend.game.Scus94491BpeSegment.executeScriptFrame(Scus94491BpeSegment.java:3598)
	at legend.game.Scus94491BpeSegment.executeScripts1(Scus94491BpeSegment.java:2988)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:1005)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:849)
	at legend.core.gpu.Gpu.lambda$run$10(Gpu.java:519)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:374)
	at legend.core.opengl.Window.run(Window.java:235)
	at legend.core.gpu.Gpu.run(Gpu.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LordMonoxide** [comment]
Another update on this: it's the script is actually allocating new script states until it runs out

**Comment by dragoonsouls** [comment]
09:25:02.408 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 67 (entry point 0x1)
09:25:02.408 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 68 (EffectManagerData6c)
09:25:02.408 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 68 (entry point 0x0)
09:25:02.408 [GPU legend.game.combat.Bttl_800e:1666] INFO : Allocating memulated effect manager 68 for BttlScriptData6cSub38 (parent: 13) @ 804e30d8 from legend.game.combat.SEffe.FUN_801052dc(SEffe.java:3334)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 68 (entry point 0x1)
09:25:02.409 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 69 (EffectManagerData6c)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 69 (entry point 0x0)
09:25:02.409 [GPU legend.game.combat.Bttl_800e:1673] INFO : Allocating effect manager 69 for AttackHitFlashEffect0c (parent: 13) from legend.game.combat.Bttl_800e.allocateAttackHitFlashEffect(Bttl_800e.java:2047)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 69 (entry point 0x1)
09:25:02.409 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 70 (EffectManagerData6c)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 70 (entry point 0x0)
09:25:02.409 [GPU legend.game.combat.Bttl_800e:1666] INFO : Allocating memulated effect manager 70 for BttlScriptData6cSub38 (parent: 13) @ 804e2ee8 from legend.game.combat.SEffe.FUN_801052dc(SEffe.java:3334)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 70 (entry point 0x1)
09:25:02.409 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 71 (EffectManagerData6c)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 71 (entry point 0x0)
09:25:02.409 [GPU legend.game.combat.Bttl_800e:1673] INFO : Allocating effect manager 71 for AttackHitFlashEffect0c (parent: 13) from legend.game.combat.Bttl_800e.allocateAttackHitFlashEffect(Bttl_800e.java:2047)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 71 (entry point 0x1)
09:25:02.409 [GPU legend.game.scripting.ScriptManager:91] INFO : Allocating script index 9 (EffectManagerData6c)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script Do nothing into index 9 (entry point 0x0)
09:25:02.409 [GPU legend.game.combat.Bttl_800e:1666] INFO : Allocating memulated effect manager 9 for BttlScriptData6cSub38 (parent: 13) @ 804e2cf8 from legend.game.combat.SEffe.FUN_801052dc(SEffe.java:3334)
09:25:02.409 [GPU legend.game.scripting.ScriptState:194] INFO : Loading script 4182/1 into index 9 (entry point 0x1)
09:25:02.409 [GPU legend.game.scripting.ScriptManager:130] ERROR: Script 13 crashed!
09:25:02.409 [GPU legend.game.scripting.ScriptManager:131] ERROR: File 4182/1[6372]
09:25:02.409 [GPU legend.game.scripting.ScriptManager:132] ERROR: Parameters:
09:25:02.409 [GPU legend.game.scripting.ScriptManager:133] ERROR:   Op param: 0x259
09:25:02.410 [GPU legend.game.scripting.ScriptManager:135] ERROR:   1: script[13].storage[15] 9
09:25:02.410 [GPU legend.game.scripting.ScriptManager:135] ERROR:   2: script[0x145e] 0x4000
09:25:02.410 [GPU legend.game.scripting.ScriptManager:138] ERROR: Storage:
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   1: 0xd
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   2: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   3: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   4: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   5: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   6: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   7: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   8: 0x90000
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   9: 0x7
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   10: 0xb
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   11: 0x11
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   12: 0x14
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   13: 0x16
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   14: 0x12
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   15: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   16: 0x9
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   17: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   18: 0xffffffff
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   19: 0x28
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   20: 0xffffec1c
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   21: 0xfffffcf6
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   22: 0xfffffc15
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   23: 0x0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   24: 0x2f
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   25: 0x12
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   26: 0x6
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   27: 0xe
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   28: 0x0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   29: 0x9
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   30: 0x9
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   31: 0xf
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   32: 0x10
09:25:02.410 [GPU legend.game.scripting.ScriptManager:140] ERROR:   33: 0x0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:143] ERROR: Call stack:
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   1: 6371
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   2: 6491
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   3: 0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   4: 0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   5: 0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   6: 0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   7: 0
09:25:02.410 [GPU legend.game.scripting.ScriptManager:149] ERROR:   8: 0
09:25:02.411 [GPU legend.core.gpu.Gpu:461] ERROR: Shutting down due to GPU exception:
java.lang.RuntimeException: An error occurred while ticking script 13
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:152)
	at legend.game.scripting.ScriptManager.tick(ScriptManager.java:23)
	at legend.game.Scus94491BpeSegment.executeLoadersAndScripts(Scus94491BpeSegment.java:779)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$44(Scus94491BpeSegment.java:705)
	at legend.core.gpu.Gpu.lambda$setStandardRenderer$8(Gpu.java:508)
	at legend.core.gpu.Gpu.lambda$run$7(Gpu.java:422)
	at legend.core.opengl.Context.draw(Context.java:91)
	at legend.core.opengl.Window$Events.onDraw(Window.java:518)
	at legend.core.opengl.Window.run(Window.java:258)
	at legend.core.gpu.Gpu.run(Gpu.java:459)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Ran out of script states
	at legend.game.scripting.ScriptManager.findFreeScriptState(ScriptManager.java:83)
	at legend.game.scripting.ScriptManager.allocateScriptState(ScriptManager.java:87)
	at legend.game.combat.Bttl_800e.allocateEffectManager(Bttl_800e.java:1649)
	at legend.game.combat.Bttl_800e.allocateAttackHitFlashEffect(Bttl_800e.java:2047)
	at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:898)
	at legend.game.scripting.ScriptState.runOp(ScriptState.java:534)
	at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:462)
	at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:126)
	... 10 more

some supporting for this thread...
