### ISSUE TITLE
Game crashes when starting FMVs with high speed multiplier

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#970]
```
java.lang.ArithmeticException: / by zero
	at legend.core.gpu.Gpu.endFrame(Gpu.java:149)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:436)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:449)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:899)
	at legend.core.GameEngine.start(GameEngine.java:219)
	at legend.game.Main.main(Main.java:23)
```

**Comment by theflyingzamboni** [comment]
Happens whenever an FMV is started with too high of a speed multiplier.
