### ISSUE TITLE
Law pod trail effect in Law Factory crashes game

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java#972]
```
java.lang.NullPointerException: Cannot read field "next_30" because "this._800d4f90.next_30" is null
	at legend.game.submap.SMap.FUN_800f0970(SMap.java:6818)
	at legend.game.submap.SMap.FUN_800f047c(SMap.java:6612)
	at legend.game.submap.SMap.renderSubmap(SMap.java:4191)
	at legend.game.submap.SMap.loadAndRenderSubmapModelAndEffects(SMap.java:4384)
	at legend.game.submap.SMap.executeSmapLoadingStage_2(SMap.java:4808)
	at legend.game.submap.SMap.tick(SMap.java:4646)
	at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:406)
	at legend.core.RenderEngine.lambda$init$1(RenderEngine.java:449)
	at legend.core.opengl.Window$Events.onDraw(Window.java:672)
	at legend.core.opengl.Window.tickFrame(Window.java:312)
	at legend.core.opengl.Action.run(Action.java:46)
	at legend.core.opengl.Action.tick(Action.java:32)
	at legend.core.opengl.Window.run(Window.java:289)
	at legend.core.RenderEngine.run(RenderEngine.java:899)
	at legend.core.GameEngine.start(GameEngine.java:219)
	at legend.game.Main.main(Main.java:23)
```

**Comment by theflyingzamboni** [comment]
Fixed by #971 because why not.
